Refreshing project
elmish/sample-react-todomvc pull request #1
Opened 2017-09-30 17:39 UTC by OlegZee

I've faced troubles when trying to start project locally. Particularly attempt to `paket update` resulted in some cryptic errors in webpack phase.
So I just created new project from template and carefully backported other files. HMR is here and seems to be partially working.

2017-09-30 17:56 UTC, MangelMaxime commented
Thanks you for taking the time of upgrading this sample :)

I made some review comments in the PR.

Can you please explain me your problem with the HMR ?

2017-10-01 02:28 UTC, OlegZee commented
Hi @MangelMaxime, cool you're responding so quickly!
What I called "partially" is that if I change line 159 (`R.h1 [] [ R.str "todos 111" ]`), it does not reflect that changes in application. But I change line 287 (`infoFooter` function) it does.

Now I guess it's because of lazyView which I believe has a purpose in this case. Nevermind, HMR is working perfectly. I'm working on your comments and thank you.

2017-10-01 06:08 UTC, MangelMaxime requested changes

2017-10-01 06:08 UTC, MangelMaxime commented on webpack.config.js
> -var plugins = isProduction
Why remove this plugins ? They should be working because I updated the Elmish docs site like 2 days ago and it was fine I think.

2017-10-01 06:08 UTC, MangelMaxime commented on webpack.config.js
> +    plugins: [["transform-runtime", {
Please remove:

```js
{
         "helpers": true,
         // We don't need the polyfills as we're already calling
         // cdn.polyfill.io/v2/polyfill.js in index.html
         "polyfill": false,
         "regenerator": false
    }]
```

We need to let babel include its polyfill and others because we are not including them at runtime in this sample.

2017-10-01 06:08 UTC, MangelMaxime commented on src/app.fs
> +|> Program.withHMR // Add the HMR support
Make it available for debug.

```fs
#if DEBUG
|> Program.withHMR
#endif
```

2017-10-01 06:08 UTC, MangelMaxime commented on src/app.fs
>  |> Program.withConsoleTrace
Make it available for debug.

```fs
#if DEBUG
|> Program.withConsoleTrace
#endif
```

You can probably encapsulate it with the HMR line.

2017-10-01 06:08 UTC, MangelMaxime commented on src/app.fs
> +            DefaultValue model // FIXME !^model
You can remove the `// FIXME !^model` 
I believe you needed to fix line because you updated `fable-react` to 1.2.x

2017-10-01 06:08 UTC, MangelMaxime commented on src/app.fs
> +          DefaultValue todo.description // FIXME !^todo.description
You can remove the `// FIXME !^todo.description` 
I believe you needed to fix line because you updated `fable-react` to 1.2.x

2017-10-01 06:08 UTC, MangelMaxime commented on paket.dependencies
> -nuget FSharp.Core  redirects:force, content:none
@forki Should we really remove this deps ?

I don't want to trigger you about implicit deps etc. Just asking an honest question here :D

IMO I would keep it.

2017-10-01 06:08 UTC, MangelMaxime commented on package.json
> +    "react": "^15.6.2",
I think you can upgrade react to version `16`.

In the process, don't hesitate to upgrade all the dependencies versions :)

2017-10-01 06:17 UTC, MangelMaxime commented
@OlegZee This is normal if you couldn't find my comments... I once again wrote them but forgot to click on "submit review"...

For the HMR problems, you are right I just take a look at the source code and as this sample use a lot of `lazyView`, `lazyView2`, `lazyView3` the HMR is made into your application but the view isn't re-render because no changes in the Model is detected when doing the `lazyView...` check inside the application.

@et1975 Any idea, if we can do something about it ?

2017-10-01 11:26 UTC, OlegZee commented on webpack.config.js
> -var plugins = isProduction
I just took webpack.config.js from template in assumption the original one was built from previous version of elmish project template. My thought was I just have to copy back a bare minimum of things.

2017-10-01 11:27 UTC, OlegZee commented on src/app.fs
> +            DefaultValue model // FIXME !^model
done

2017-10-01 11:34 UTC, OlegZee commented on webpack.config.js
> +    plugins: [["transform-runtime", {
Done.

2017-10-01 11:35 UTC, OlegZee commented on webpack.config.js
> -var plugins = isProduction
Now I'm going to look through webpack.config.js history to get thoughful changes back.

2017-10-01 12:01 UTC, OlegZee commented on webpack.config.js
> -var plugins = isProduction
Reverted everything from original webpack.config. I see production build is published somewhere and all these things are important.

2017-10-01 12:01 UTC, OlegZee commented
Applied all changes. Thank you for your input and guidance.

2017-10-01 14:01 UTC, et1975 commented
regarding `lazyView`: primary reason for this sample is apples-to-apples syntax and performance comparison with Elm, Evan is using it there so I used it here. If HMR conflicts with `lazy` I'd rather remove HMR than introduce a workaround.

2017-10-01 14:29 UTC, MangelMaxime commented
Sure, was just asking if we had a way to "force" a full reload as we are in development. 

Let's remove it from this sample so.

2017-10-01 14:34 UTC, et1975 commented
Sure, conditional region wrapping `lazy` in Release will do the trick. However I'd say when you really need to use `lazy` calling it conditionally is usually not an option.

2017-10-01 15:09 UTC, MangelMaxime commented
You are right let's remove it so.

2017-10-01 18:31 UTC, alfonsogarciacaro commented
Quick and dirty idea (as my ideas usually are :wink:): Make HMR update a global counter and then within `lazyView` have some code (wrapped by `#if DEBUG`) that checks if this counter has been update.

2017-10-02 11:44 UTC, et1975 commented
Waiting on Oleg and Maxime to finalize the review, but on the global var check - that's a firm "negative". The way I see HMR is, yes, we're trying to optimize developer workflow, but not all solutions have to be technical - document somewhere that `lazyView` + HMR + a change in the view code means you have to trigger the render yourself.
I'm more concerned with what happens when you modify the model (type) and HMR tries to apply that... runtime exception?

2017-10-02 12:56 UTC, MangelMaxime commented
@et1975 I do agree about the global check. I will add an explanation for HMR + `lazyView`

I just encounter the case of "Updating the model and using HMR". Indeed, you will generally have runtime exception. Telling you that the reference is undefined.

2017-10-02 13:33 UTC, OlegZee commented
@MangelMaxime, @et1975 would you mind guys the following snipped on top of views definition?
```fsharp
#if DEBUG
// lazyView prevents HMR to re-render the view so switching off
let lazyView, lazyView2, lazyView3 = id, id, id
#endif
```
I pushed the app.fs with HMR turned off (updated packet files too).

2017-10-02 13:43 UTC, et1975 commented
> would you mind guys the following snippet on top of views definition?

Again, I'd like to keep it on par with the Elm impl.

2017-10-02 14:04 UTC, MangelMaxime commented
@et1975 This seems ok for me.

2017-10-02 14:09 UTC, merged

2017-10-03 18:26 UTC, et1975 commented
Thanks, published the updated sample!